---
title: "Multiple_graphs_Br"
author: "Leandro"
date: "04/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(flexdashboard)
library(tidyverse)
library(plotly)
library(sidrar)
library(viridis)
library(ggplot2)

# Some color schemes: 

# hex msafra: #4c1211
# rgb msafra: 761817
# plotlyColors <-   c('#1f77b4',  # muted blue
#                     '#ff7f0e',  # safety orange
#                     '#2ca02c',  # cooked asparagus green
#                     '#d62728',  # brick red
#                     '#9467bd',  # muted purple
#                     '#8c564b',  # chestnut brown
#                     '#e377c2',  # raspberry yogurt pink
#                     '#7f7f7f',  # middle gray
#                     '#bcbd22',  # curry yellow-green
#                     '#17becf')  # blue-teal

 plotlyColors <- c(viridis(100))

# Setting time span: Watch out the time of updating
dias <- ceiling(difftime(Sys.Date(), "2020-01-22", units = "days")) #-1

# Choose here the path to output png plots:
ggpath  <- "C:/Users/Padulla/Documents/GitHub/corona_dash/"
Here    <- Sys.Date()
HereUSA <- Here - 0
HereBR  <- Here - 0

# loading stuff
source("Functions.R")
source("Brazil.R")



```

```{r}
library(plotly)

# Dates | Al | AC | 
dz <- 
BrDeaths %>% 
  t %>% 
  as_tibble %>% 
  mutate_all(~ . - lag(.)) %>% 
  mutate(Dates = as.Date(colnames(BrDeaths), format = "%m/%d/%y") ) %>% 
  select(Dates, everything()) %>% 
  mutate_if(~ any(is.na(.)), ~ if_else(is.na(.), 0, .))

dw <- 
do.call(cbind, lapply(colnames(dz)[-1], function(x) TTR::SMA(dz[,x], 7))) %>% 
  as_tibble %>% 
  rename_all(~ paste0('M',colnames(dz)[-1])) %>% 
  mutate_if(~ any(is.na(.)), ~ if_else(is.na(.), 0, .)) 

dh <- 
cbind(dz, dw) %>% 
  as_tibble %>% 
  filter(Dates >= as.Date("2020-03-20"))

f2 <- list(family = 'Old Standard TT, serif', size = 14, color = plotlyColors[1])

plots <- 
lapply(colnames(dh)[2:29], function(x){ 
                           expr   <- paste0("~", "`", x, "`")
                           mexpr  <- paste0("~", "`", "M", x, "`")
                           legm   <- paste0("Moving average of ", x)
                           a <- list(
                                      text = x,
                                      font = f2,
                                      xref = "paper",
                                      yref = "paper",
                                      yanchor = "bottom",
                                      xanchor = "center",
                                      align = "center",
                                      x = 0.5,
                                      y = 1,
                                      showarrow = FALSE
                                    )
                           plot_ly(dh, x = ~Dates) %>% 
                             add_trace(y = as.formula(expr),  type = 'bar', marker = list(color = plotlyColors[1])) %>% 
                             add_trace(y = as.formula(mexpr), type = 'scatter', mode = 'lines', line = list(color = plotlyColors[2]) ) %>% 
                             layout(showlegend = FALSE, annotations = a)
})
names(plots) <- colnames(dz)[-c(1, length(dz))]
p <- subplot(plots, nrows = 7, shareX = FALSE, shareY = FALSE)
p
```


